include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_typing_uninitialized_variables: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_constructors: warning
    avoid_print: warning
    prefer_const_literals_to_create_immutables: warning
